//! Owned in-memory and generated byte streams only; no private source access.
use sha2::{Digest, Sha256};
use std::io::{self, Cursor, Read, Seek, SeekFrom};
use stepsemble_history_source_reader::jsonl_scan::{
    self, CHUNK_BYTES, Error, PAGE_BYTES, RECORD_BYTES, RECORDS, SOURCE_BYTES, Selection,
    scan_matching_page,
};

fn selection(offset: u32, limit: u32) -> Selection {
    Selection { offset, limit }
}

fn read(bytes: &[u8], offset: u32, limit: u32) -> Result<jsonl_scan::Page, Error> {
    scan_matching_page(
        &mut Cursor::new(bytes),
        bytes.len() as u64,
        selection(offset, limit),
        None,
        || Ok(()),
        |_, _, _| Ok(()),
    )
}

#[test]
fn exact_bytes_offsets_crlf_blank_unknown_and_binary_are_not_rewritten() {
    // This scanner is deliberately below UTF-8/JSON semantics. Future callers
    // must validate them explicitly; binary bytes are not silently repaired.
    let lines = [
        "{\"type\":\"session_meta\",\"text\":\"貓🐾\"}\r\n".as_bytes(),
        b" \t\r\n",
        b"{\"type\":\"future_record\"}\n",
        b"\xff\0\n",
    ];
    let bytes = lines.concat();
    for offset in 0..=lines.len() {
        let page = read(&bytes, offset as u32, 2).unwrap();
        assert_eq!(page.summary.byte_length, bytes.len() as u64);
        assert_eq!(page.summary.record_count, lines.len() as u32);
        assert_eq!(
            page.summary.sha256,
            <[u8; 32]>::from(Sha256::digest(&bytes))
        );
        let end = (offset + 2).min(lines.len());
        assert_eq!(page.records.len(), end - offset);
        assert_eq!(page.next_offset, (end < lines.len()).then_some(end as u32));
        for (index, row) in page.records.iter().enumerate() {
            let i = index + offset;
            assert_eq!(row.record_index, i as u32);
            assert_eq!(
                row.byte_offset,
                lines[..i].iter().map(|s| s.len() as u64).sum::<u64>()
            );
            assert_eq!(row.bytes, lines[i]);
            assert_eq!(row.sha256, <[u8; 32]>::from(Sha256::digest(lines[i])));
        }
    }
}

struct Fragmented<'a> {
    source: Cursor<&'a [u8]>,
    chunk: usize,
    largest_read: usize,
}
impl Read for Fragmented<'_> {
    fn read(&mut self, target: &mut [u8]) -> io::Result<usize> {
        self.largest_read = self.largest_read.max(target.len());
        let length = target.len().min(self.chunk);
        self.source.read(&mut target[..length])
    }
}
impl Seek for Fragmented<'_> {
    fn seek(&mut self, position: SeekFrom) -> io::Result<u64> {
        self.source.seek(position)
    }
}

#[test]
fn read_fragmentation_including_utf8_and_crlf_splits_does_not_change_results() {
    let bytes = format!("{}\r\n{}\n\n", "貓🐾".repeat(9400), "a".repeat(66000)).into_bytes();
    let expected = read(&bytes, 1, 50).unwrap();
    for chunk in [
        1,
        2,
        3,
        7,
        4095,
        CHUNK_BYTES - 1,
        CHUNK_BYTES,
        CHUNK_BYTES + 1,
    ] {
        let mut reader = Fragmented {
            source: Cursor::new(&bytes),
            chunk,
            largest_read: 0,
        };
        let mut seen = 0;
        let actual = scan_matching_page(
            &mut reader,
            bytes.len() as u64,
            selection(1, 50),
            None,
            || Ok(()),
            |index, _, line| {
                assert_eq!(index, seen);
                assert!(line.ends_with(b"\n"));
                seen += 1;
                Ok(())
            },
        )
        .unwrap();
        assert_eq!(seen, 3); // Validation is once, not twice with side effects.
        assert_eq!(actual, expected);
        assert!(reader.largest_read <= CHUNK_BYTES);
    }
}

#[test]
fn page_budget_stops_at_whole_record_and_next_offset_never_skips() {
    let mut large = vec![b'a'; RECORD_BYTES];
    large[RECORD_BYTES - 1] = b'\n';
    let bytes = [large.as_slice(), large.as_slice(), b"end\n"].concat();
    let first = read(&bytes, 0, 50).unwrap();
    assert_eq!(first.records.len(), 2);
    assert_eq!(
        first.records.iter().map(|r| r.bytes.len()).sum::<usize>(),
        PAGE_BYTES
    );
    assert_eq!(first.next_offset, Some(2));
    let last = read(&bytes, 2, 50).unwrap();
    assert_eq!(last.records[0].byte_offset, PAGE_BYTES as u64);
    assert_eq!(last.records[0].bytes, b"end\n");
    assert_eq!(last.next_offset, None);
}

#[test]
fn invalid_selection_and_source_bounds_do_not_read_or_validate() {
    struct Unreadable;
    impl Read for Unreadable {
        fn read(&mut self, _: &mut [u8]) -> io::Result<usize> {
            panic!("must not read")
        }
    }
    impl Seek for Unreadable {
        fn seek(&mut self, _: SeekFrom) -> io::Result<u64> {
            panic!("must not seek")
        }
    }
    for (size, selected, error) in [
        (0, selection(0, 1), Error::Empty),
        (SOURCE_BYTES + 1, selection(0, 1), Error::SourceLimit),
        (u64::MAX, selection(0, 1), Error::SourceLimit),
        (10, selection(0, 0), Error::InvalidSelection),
        (10, selection(0, 51), Error::InvalidSelection),
        (10, selection(RECORDS + 1, 1), Error::InvalidSelection),
        (10, selection(u32::MAX, u32::MAX), Error::InvalidSelection),
    ] {
        assert_eq!(
            scan_matching_page(
                &mut Unreadable,
                size,
                selected,
                None,
                || panic!("no callback"),
                |_, _, _| panic!("no validation")
            ),
            Err(error)
        );
    }
    assert_eq!(read(b"x\n", 2, 1), Err(Error::InvalidSelection));
    assert!(read(b"x\n", 1, 1).unwrap().records.is_empty());
}

#[test]
fn tail_or_oversized_record_after_a_full_selected_page_still_rejects_everything() {
    assert_eq!(read(b"ok\nbroken", 0, 1), Err(Error::IncompleteTail));
    let bytes = [b"ok\n".as_slice(), &vec![b'a'; RECORD_BYTES], b"\n"].concat();
    assert_eq!(read(&bytes, 0, 1), Err(Error::RecordLimit));
    let bytes = [b"ok\n".as_slice(), &vec![b'a'; RECORD_BYTES]].concat();
    assert_eq!(read(&bytes, 0, 1), Err(Error::IncompleteTail));
    let bytes = [b"ok\n".as_slice(), &vec![b'a'; RECORD_BYTES + 1]].concat();
    assert_eq!(read(&bytes, 0, 1), Err(Error::RecordLimit));
}

#[test]
fn exact_record_count_cap_and_one_over_are_checked_after_the_requested_page() {
    let mut bytes = vec![b'\n'; RECORDS as usize];
    let result = read(&bytes, RECORDS - 1, 50).unwrap();
    assert_eq!(result.summary.record_count, RECORDS);
    assert_eq!(result.records.len(), 1);
    assert_eq!(result.next_offset, None);
    bytes.push(b'\n');
    assert_eq!(read(&bytes, 0, 1), Err(Error::RecordLimit));
}

#[test]
fn semantic_validator_must_accept_the_entire_source_before_a_page_can_escape() {
    let bytes = b"{\"type\":\"known\"}\nnot json\n";
    let result = scan_matching_page(
        &mut Cursor::new(bytes),
        bytes.len() as u64,
        selection(0, 1),
        None,
        || Ok(()),
        |_, _, line| {
            serde_json::from_slice::<serde_json::Value>(line)
                .map(|_| ())
                .map_err(|_| Error::InvalidRecord)
        },
    );
    assert_eq!(result, Err(Error::InvalidRecord));
}

#[test]
fn stale_expected_summary_rejects_digest_length_and_count_changes() {
    let bytes = b"a\nb\n";
    let expected = read(bytes, 0, 1).unwrap().summary;
    for summary in [
        jsonl_scan::Summary {
            sha256: [0; 32],
            ..expected
        },
        jsonl_scan::Summary {
            byte_length: expected.byte_length + 1,
            ..expected
        },
        jsonl_scan::Summary {
            record_count: expected.record_count + 1,
            ..expected
        },
    ] {
        assert_eq!(
            scan_matching_page(
                &mut Cursor::new(bytes),
                bytes.len() as u64,
                selection(1, 1),
                Some(summary),
                || Ok(()),
                |_, _, _| Ok(())
            ),
            Err(Error::Changed)
        );
    }
    assert_eq!(
        scan_matching_page(
            &mut Cursor::new(bytes),
            bytes.len() as u64,
            selection(1, 1),
            Some(expected),
            || Ok(()),
            |_, _, _| Ok(())
        )
        .unwrap()
        .records[0]
            .bytes,
        b"b\n"
    );
}

#[test]
fn growth_and_shrink_never_turn_into_a_successful_prefix() {
    for size in [1, 3, 5] {
        assert_eq!(
            scan_matching_page(
                &mut Cursor::new(b"a\nb\n"),
                size,
                selection(0, 1),
                None,
                || Ok(()),
                |_, _, _| Ok(())
            ),
            Err(Error::Changed)
        );
    }
}

struct Mutating {
    reader: Cursor<Vec<u8>>,
    second: Vec<u8>,
    seeks: u32,
}
impl Read for Mutating {
    fn read(&mut self, target: &mut [u8]) -> io::Result<usize> {
        self.reader.read(target)
    }
}
impl Seek for Mutating {
    fn seek(&mut self, position: SeekFrom) -> io::Result<u64> {
        self.seeks += 1;
        if self.seeks == 2 {
            *self.reader.get_mut() = self.second.clone();
        }
        self.reader.seek(position)
    }
}

#[test]
fn second_scan_detects_same_size_changes_in_unselected_records() {
    for second in [
        b"a\nz\n".to_vec(),
        b"a\n".to_vec(),
        b"a\nb\nx\n".to_vec(),
        b"a\nb!".to_vec(),
    ] {
        let mut reader = Mutating {
            reader: Cursor::new(b"a\nb\n".to_vec()),
            second,
            seeks: 0,
        };
        let result = scan_matching_page(
            &mut reader,
            4,
            selection(0, 1),
            None,
            || Ok(()),
            |_, _, _| Ok(()),
        );
        assert!(matches!(
            result,
            Err(Error::Changed | Error::IncompleteTail)
        ));
        assert_eq!(reader.seeks, 2);
    }
}

#[test]
fn cancellation_and_deadline_are_checked_inside_dense_chunks_and_both_scans() {
    let bytes = vec![b'\n'; 100];
    for error in [Error::Cancelled, Error::Budget] {
        // Visit every checkpoint, including before the second seek and after
        // the final EOF read. No successful first page bypasses cancellation.
        let mut total = 0;
        scan_matching_page(
            &mut Cursor::new(&bytes),
            bytes.len() as u64,
            selection(0, 1),
            None,
            || {
                total += 1;
                Ok(())
            },
            |_, _, _| Ok(()),
        )
        .unwrap();
        for stop_at in 1..=total {
            let mut count = 0;
            assert_eq!(
                scan_matching_page(
                    &mut Cursor::new(&bytes),
                    bytes.len() as u64,
                    selection(0, 1),
                    None,
                    || {
                        count += 1;
                        if count == stop_at { Err(error) } else { Ok(()) }
                    },
                    |_, _, _| Ok(())
                ),
                Err(error)
            );
        }
    }
}

#[test]
fn interrupted_reads_are_bounded_by_checkpoint_and_io_errors_are_not_swallowed() {
    struct Faulty {
        interrupted: bool,
    }
    impl Read for Faulty {
        fn read(&mut self, _: &mut [u8]) -> io::Result<usize> {
            Err(io::Error::from(if self.interrupted {
                io::ErrorKind::Interrupted
            } else {
                io::ErrorKind::Other
            }))
        }
    }
    impl Seek for Faulty {
        fn seek(&mut self, _: SeekFrom) -> io::Result<u64> {
            Ok(0)
        }
    }
    let mut ticks = 0;
    assert_eq!(
        scan_matching_page(
            &mut Faulty { interrupted: true },
            10,
            selection(0, 1),
            None,
            || {
                ticks += 1;
                if ticks > 30 {
                    Err(Error::Budget)
                } else {
                    Ok(())
                }
            },
            |_, _, _| Ok(())
        ),
        Err(Error::Budget)
    );
    assert_eq!(
        scan_matching_page(
            &mut Faulty { interrupted: false },
            10,
            selection(0, 1),
            None,
            || Ok(()),
            |_, _, _| Ok(())
        ),
        Err(Error::Io)
    );
}

#[test]
fn failed_or_mispositioned_rewind_never_yields_a_page() {
    struct FailedSeek {
        reader: Cursor<&'static [u8]>,
        seeks: usize,
        fail_at: usize,
        wrong_position: bool,
    }
    impl Read for FailedSeek {
        fn read(&mut self, target: &mut [u8]) -> io::Result<usize> {
            self.reader.read(target)
        }
    }
    impl Seek for FailedSeek {
        fn seek(&mut self, position: SeekFrom) -> io::Result<u64> {
            self.seeks += 1;
            if self.seeks == self.fail_at {
                return if self.wrong_position {
                    Ok(1)
                } else {
                    Err(io::ErrorKind::Other.into())
                };
            }
            self.reader.seek(position)
        }
    }
    for fail_at in [1, 2] {
        for wrong_position in [false, true] {
            let mut reader = FailedSeek {
                reader: Cursor::new(b"a\nb\n"),
                seeks: 0,
                fail_at,
                wrong_position,
            };
            assert_eq!(
                scan_matching_page(
                    &mut reader,
                    4,
                    selection(0, 1),
                    None,
                    || Ok(()),
                    |_, _, _| Ok(())
                ),
                Err(Error::Io)
            );
            assert_eq!(reader.seeks, fail_at);
        }
    }
}

#[test]
fn transient_interrupted_read_retries_without_losing_a_record_or_consuming_bytes() {
    struct Once {
        reader: Cursor<&'static [u8]>,
        interrupted: bool,
    }
    impl Read for Once {
        fn read(&mut self, target: &mut [u8]) -> io::Result<usize> {
            if !self.interrupted {
                self.interrupted = true;
                return Err(io::ErrorKind::Interrupted.into());
            }
            self.reader.read(target)
        }
    }
    impl Seek for Once {
        fn seek(&mut self, position: SeekFrom) -> io::Result<u64> {
            self.interrupted = false;
            self.reader.seek(position)
        }
    }
    let mut reader = Once {
        reader: Cursor::new(b"a\nb\n"),
        interrupted: false,
    };
    assert_eq!(
        scan_matching_page(
            &mut reader,
            4,
            selection(0, 1),
            None,
            || Ok(()),
            |_, _, _| Ok(())
        )
        .unwrap(),
        read(b"a\nb\n", 0, 1).unwrap()
    );
}

/// Generates a large stream without allocating that stream. The sole fixture
/// backing buffer is one line. Real memory measurements live in a separate gate.
struct Repeated {
    line: Vec<u8>,
    count: u32,
    position: u64,
    total_read: u64,
    largest_read: usize,
}
impl Read for Repeated {
    fn read(&mut self, target: &mut [u8]) -> io::Result<usize> {
        self.largest_read = self.largest_read.max(target.len());
        let size = self.line.len() as u64 * u64::from(self.count);
        let n = target.len().min((size - self.position) as usize);
        let mut used = 0;
        while used < n {
            let offset = self.position as usize % self.line.len();
            let length = (n - used).min(self.line.len() - offset);
            target[used..used + length].copy_from_slice(&self.line[offset..offset + length]);
            used += length;
            self.position += length as u64;
        }
        self.total_read += n as u64;
        Ok(n)
    }
}
impl Seek for Repeated {
    fn seek(&mut self, position: SeekFrom) -> io::Result<u64> {
        if position != SeekFrom::Start(0) {
            return Err(io::ErrorKind::InvalidInput.into());
        }
        self.position = 0;
        Ok(0)
    }
}

#[test]
fn large_generated_history_above_old_byte_and_record_limits_retains_only_one_page() {
    let mut line = vec![b'a'; 1024];
    line[1023] = b'\n';
    let mut source = Repeated {
        line,
        count: 20_000,
        position: 0,
        total_read: 0,
        largest_read: 0,
    };
    let size = source.line.len() as u64 * u64::from(source.count);
    let mut validated = 0;
    let result = scan_matching_page(
        &mut source,
        size,
        selection(19_997, 50),
        None,
        || Ok(()),
        |index, offset, line| {
            assert_eq!(index, validated);
            assert_eq!(offset, u64::from(index) * 1024);
            assert_eq!(line.len(), 1024);
            validated += 1;
            Ok(())
        },
    )
    .unwrap();
    assert_eq!(validated, 20_000);
    assert_eq!(result.summary.record_count, 20_000);
    assert_eq!(result.summary.byte_length, size);
    assert_eq!(result.records.len(), 3);
    assert_eq!(
        result.records.iter().map(|r| r.bytes.len()).sum::<usize>(),
        3072
    );
    assert_eq!(result.records[0].record_index, 19_997);
    assert_eq!(result.records[0].byte_offset, 19_997 * 1024);
    assert_eq!(result.next_offset, None);
    assert_eq!(source.total_read, size * 2);
    assert!(source.largest_read <= CHUNK_BYTES);
}
